### ISSUE TITLE
Blahaj for a texturepack

### ISSUE THREAD

**Issue by recom1** [Hibiii/Blahaj#13]
would it be possible to use the blahaj model in a texture pack as a totem i know it would not be possible regularly but with optifine models it seams possible

**Comment by hibiii** [comment]
It's possible even without OptiFine, the Blåhaj model is a normal item model much like the fence or wall items, the only thing special about it is the code that angles the arms in to make a hugging pose but otherwise it works with any other item.

You'll have to tweak the model's positioning so it looks right in the hand in third person because it was positioned based on that hugging pose, but other than that, it's as easy as it gets!
